### ISSUE TITLE
Identifiers not sorted in case-insensitive alpha order in Outline

### ISSUE THREAD

**Issue by flashjazzcat** [peterdell/wudsn-ide#1]
Sorting identifiers in the Outline view results in case-sensitive ordering:

![2081446449_Screenshot2021-11-02210538 png 8a0a04bc29f26298f6cbc2112befc6f0](https://user-images.githubusercontent.com/7622152/140538844-842adef4-744a-44c4-985c-0ccc6ceb8334.png)

**Comment by peterdell** [comment]
This was already fixed with 3db927c9f196bcd105dcceb98d3197bf506426d2 in 11/2021. The latest build all include the correction,
