### ISSUE TITLE
Font is not mono-spaces in block selection mode

### ISSUE THREAD

**Issue by peterdell** [peterdell/wudsn-ide#5]
On Linux, when I switch to block selection mode spaces and some other texts get a smaller width:
Normal mode:
![image](https://user-images.githubusercontent.com/10855380/211664200-0edfebf5-f4d8-4098-86a5-76d34f55d172.png)

Block selection mode:
![image](https://user-images.githubusercontent.com/10855380/211664222-d006730e-7cce-4277-9a1d-3c48077b86f1.png)

From: pirx

**Comment by ehn-pkalinowski** [comment]
The new version has got it totally fixed! Thanks!

**Comment by peterdell** [comment]
Thanks for confirming.
